[project]
name = "als-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "leonaidasup", email = "111338890+leonaidasup@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
als-detection = "als_detection:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "src/als_detection",
    "backend",
]
